version: '3.9'


networks:
  demo:
    driver: bridge

services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: a123456789
      POSTGRES_DB: demo
    volumes:
      - ./data/database.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - demo


  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: a123456789
      PGADMIN_DEFAULT_EMAIL: test@test.com
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - demo

  api:
    build: ./
    container_name: api
    restart: always
    ports:
      - 3000:3000
    environment:
      CONNECTION_STRING: postgres://postgres:a123456789@postgres:5432/demo
    depends_on:
      - postgres
    networks:
      - demo
